spring:
  profiles:
    active:
    - dev
---

server:
  port: 8761
spring:
  profiles: dev
  application:
    name: ichong-eureka-git
eureka:
  instance:
    hostname: eureka-server  # eureka实例的主机名
  client:
    register-with-eureka: false #不把自己注册到eureka上
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
       defaultZone:  http://localhost:8761/eureka/    #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
       #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/